version: '3.3'
services:
  feishu-chatgpt:
    container_name: feishu-chatgpt
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000/tcp"
    # volumes:
    #   - ./code/config.yaml:/app/config.yaml:ro
    environment:
      - APP_ID=cli_a7b2b9c333f9d00c
      - APP_SECRET=f33fOV2yh2jdMklr8IANme7JGUHMJlVt
      - APP_ENCRYPT_KEY=v4UOSG4KPrSTnpJZtEHEcfarq6yFXtFd
      - APP_VERIFICATION_TOKEN=4pEwg80ifNJa3A2Ka9Ph5gyHpFGnyToN
      # 请确保和飞书应用管理平台中的设置一致
      - BOT_NAME=ChatGPT
      # OpenAI API Key 支持负载均衡, 可以填写多个 Key 用逗号分隔
      - OPENAI_KEY=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,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
      # 服务器配置
      - HTTP_PORT=9000
      - HTTPS_PORT=9001
      - USE_HTTPS=false
      - CERT_FILE=cert.pem
      - KEY_FILE=key.pem
      # OpenAI 地址, 一般不需要修改, 除非你有自己的反向代理
      - API_URL=https://api.openai.com
      # 代理设置, 例如 - HTTP_PROXY=http://127.0.0.1:7890, 默认代表不使用代理
      - HTTP_PROXY
